### ISSUE TITLE
namu.wiki

### ISSUE THREAD

**Issue by ghost** [List-KR/List-KR-Script#1]
Moved from https://github.com/yous/YousList/issues/198.

**Comment by tempo001** [comment]
This works for now but it will not work when they change the class name.
Temporary I comment the filter that works now.
`namu.wiki##img.cNlx2saq:nth-ancestor(4)`

**Comment by piquark6046** [comment]
Tested with 1.0d62.
<details>
<summary>Screenshot</summary>

![Screenshot1](https://user-images.githubusercontent.com/98787049/154853503-a1f4016d-5baf-419a-9a78-2668a697ae8c.png)

</details>

**Comment by piquark6046** [comment]
Resolved.

**Comment by piquark6046** [comment]
@Gaeulbyul
Can you test it?

**Comment by gaeulbyul** [comment]
@piquark6046 I tested it with 3 environments, but none are works...

(All browsers are tested with a clean profile in Windows Sandbox)

* Firefox: v97.0.1
  * Tampermonkey: v4.14.6136
  * AdGuard: v3.6.17
* Chrome: v98.0.4758.102 (stable)
  * Tampermonkey: v4.14
  * AdGuard: v3.6.17
  * (Extensions are downloaded from Chrome Web Store)
* MSEdge: v98.0.1108.62 (Stable)
  * Tampermonkey: v4.13.6138
  * AdGuard: v3.6.17
  * (Extensions are downloaded from MS Edge Addons)

Console messages:
* `Platform browser has already been set. Overwriting the platform with [object Object].`
* `webgl backend was already registered. Reusing existing backend factory.`
* `The kernel '_FusedMatMul' for backend 'webgl' is already registered`
* `The kernel 'Abs' for backend 'webgl' is already registered`
* (...and many "already registered" messages)

**Comment by piquark6046** [comment]
@gaeulbyul Can you check your inbox?
`83921e78f6b3e431c58471e21d1ed01cb7263637`

**Comment by tea91** [comment]
> @gaeulbyul Can you test it?

I'd check for android. But not work.

![Screenshot_2022-03-02-08-41-04-557_com sec android app sbrowser](https://user-images.githubusercontent.com/1233030/156272532-6e2d80c0-7388-47d2-bce1-a38e302b887e.jpg)

**Comment by piquark6046** [comment]
@tea91 
It seems that you use Samsung Internet, and does not use [AdGuard for Android](https://adguard.com/en/adguard-android/overview.html).
If so, please install AdGuard for Android. Not [AdGuard Content Blocker](https://play.google.com/store/apps/details?id=com.adguard.android.contentblocker).

**Comment by piquark6046** [comment]
@tempo001 @kwon0408 @lemonNsoda
Please install List-KR Script 1.0.2, if you use Tampermonkey.

**Comment by tea91** [comment]
> @tea91 It seems that you use Samsung Internet, and don't use [AdGuard for Android](https://adguard.com/en/adguard-android/overview.html). If so, please install AdGuard for Android. Not [AdGuard Content Blocker](https://play.google.com/store/apps/details?id=com.adguard.android.contentblocker).

Thx but i tried on chrome with adguard for andriod and adguard content bloker(for samsung internet).
Unfortunately, not work all. even with script.

![Screenshot_2022-03-02-22-26-13-588_com android chrome](https://user-images.githubusercontent.com/1233030/156372045-8c40162b-11d6-4ea9-8451-b91011f248f7.jpg)
![Screenshot_2022-03-02-22-26-38-769_com adguard android](https://user-images.githubusercontent.com/1233030/156372098-680c8720-554c-4d1f-8d8f-22fe2fc54f23.jpg)
![Screenshot_2022-03-02-22-27-10-529_com adguard android](https://user-images.githubusercontent.com/1233030/156372112-b526bc9b-2421-4961-9621-848f9afa3d73.jpg)
![Screenshot_2022-03-02-22-29-39-413_com sec android app sbrowser](https://user-images.githubusercontent.com/1233030/156372125-4a00689b-990e-4513-b059-bd5bc5c62c98.jpg)
![Screenshot_2022-03-02-22-30-15-928_com android chrome](https://user-images.githubusercontent.com/1233030/156372136-896451d8-4a3c-485d-a928-379f8a21f96a.jpg)
![Screenshot_2022-03-02-22-30-50-991_com adguard android](https://user-images.githubusercontent.com/1233030/156372146-bc36a202-be1e-4cd1-8bd9-2707fcd8f84c.jpg)

Plz edit hiding screenshots idk how to do.

**Comment by piquark6046** [comment]
@tea91 
Please enable HTTPS filtering feature of AdGuard for Android.
And, add List-KR Script as an userscript at extension section of AdGuard, not custom filters.

---

You can hide a content by using `<details>`.

```
<details>
<summary>Summary</summary>

Content

</details>
```

**Comment by tea91** [comment]
> @tea91 Please enable HTTPS filtering feature of AdGuard for Android. And, add List-KR Script as an userscript at extension section of AdGuard, not custom filters.
> 
> You can hide a content by using `<details>`.
> 
> ```
> <details>
> <summary>Summary</summary>
> 
> Content
> 
> </details>
> ```

Am I something wrong? Its not work. 

![Screenshot_2022-03-02-23-10-02-778_com adguard android](https://user-images.githubusercontent.com/1233030/156378881-1fca3b7a-c036-47c6-b98f-639eef88f7e7.jpg)
![Screenshot_2022-03-02-23-10-21-593_com adguard android](https://user-images.githubusercontent.com/1233030/156378892-249963d0-c20b-4695-935c-d8db4f25c5f0.jpg)
![Uploading Screenshot_2022-03-02-23-11-34-872_com.android.chrome.jpg…]()

**Comment by piquark6046** [comment]
@tea91 
Then, please reload the website.

**Comment by tea91** [comment]
> @tea91 Please enable HTTPS filtering feature of AdGuard for Android. And, add List-KR Script as an userscript at extension section of AdGuard, not custom filters.
> 
> You can hide a content by using `<details>`.
> 
> ```
> <details>
> <summary>Summary</summary>
> 
> Content
> 
> </details>
> ```

Am I something wrong? Its not work yet 

![Screenshot_2022-03-02-23-19-25-360_com adguard android](https://user-images.githubusercontent.com/1233030/156379490-01992157-25f2-4f1c-93c4-fdb54b842d51.jpg)
![Screenshot_2022-03-02-23-10-21-593_com adguard android](https://user-images.githubusercontent.com/1233030/156379533-5d3e23ba-a1d4-4b25-bf51-2326ea820af5.jpg)
![Screenshot_2022-03-02-23-11-34-872_com android chrome](https://user-images.githubusercontent.com/1233030/156379550-b34456b2-a6b1-4a51-9ca3-329158772cd3.jpg)

**Comment by piquark6046** [comment]
@tea91 
Then, please reload the website.

**Comment by tea91** [comment]
> @tea91 Then, please reload the website.

Yes i did. Delete cache and reload. But its not worked yet.

**Comment by piquark6046** [comment]
@tea91 
Can you use your personal computer?

**Comment by piquark6046** [comment]
@tea91 
What is the version and detail of your Android operating system?

Is data compression of a web browser enabled?
If so, please disable it.

**Comment by tea91** [comment]
> 
Android 11 Rp1a.200720.011 

Nope. Just normal samsung internet and chrome setting.

I fixed it by adding this(https://github.com/Apious/Ads_Filter_Contents/blob/1st/Ads_Filter_Contents.txt).

**Comment by piquark6046** [comment]
@tea91 
Can you follow [this guide](https://kb.adguard.com/en/android/solving-problems/manual-certificate)?

---

I don't strongly recommend adding Apious' Ads_Filter_Content.txt into your custom filters.
Because, It can cause an incorrect blocking issue. ( [example](https://github.com/Apious/Ads_Filter_Contents/blob/5c93f06d2ef4bbc6dc62c9453725d860b723e842/Ads_Filter_Contents.txt#L496) )

**Comment by piquark6046** [comment]
@tea91 
Today, I found that PowerLink advertisement is not blocked even if the website is reloaded.
I am working on it.
