### ISSUE TITLE
AD: 

### ISSUE THREAD

**Issue by 2019mikelee** [List-KR/List-KR-Script#13]
### URL

https://namu.wiki/w/%EB%B0%94%EB%B3%B4%EC%83%81%EC%9E%90?noredirect=1

 redirect 부분에서는 차단이 되지 않는듯 합니다.

### Channel

Dev

### Browser

Google Chrome

### Platform

Tampermonkey

**Comment by piquark6046** [comment]
List-KR Script exists to block complex advertisement that cannot be blocked by a regular ad-blocking extension.
However, for now, the PowerLink advertisement on namu.wiki can be blocked with [List-KR](https://github.com/List-KR/List-KR).

Please use List-KR instead of List-KR Script.
