### ISSUE TITLE
Ad-Shield: ygosu ppss inven mlbpark sports.donga.com tgd.kr

### ISSUE THREAD

**Issue by ghost** [List-KR/List-KR-Script#2]
https://docs.ad-shield.io/guide/advertiser
https://docs.ad-shield.io/guide/ads-size

**Comment by piquark6046** [comment]
https://github.com/AdguardTeam/AdGuardExtra/issues/294#issuecomment-1037343739
https://github.com/AdguardTeam/AdGuardExtra/issues/294#issuecomment-1037360582

**Comment by gaeulbyul** [comment]
Hello, I just noticed that there are more sites with ad-shield ads:
* https://mlbpark.donga.com/
* https://sports.donga.com/

**Comment by piquark6046** [comment]
@gaeulbyul Where?
<details>
<summary>Screenshots</summary>

![Screenshote](https://user-images.githubusercontent.com/98787049/154799137-6183496c-1b48-4369-bce0-e7ca1a8ce549.png)
![Screenshotq](https://user-images.githubusercontent.com/98787049/154799141-8b84f803-23e8-460f-8358-03c0f996bc06.png)


</details>

**Comment by gaeulbyul** [comment]
Oops, I'm sorry. Actually it was just a script tag but there's no ads (yet?)

```html
<script src='https://cdn.jsdelivr.net/npm/@adshield/web-script@latest/dist/script.min.js'></script>
<meta name='adshield-analytics-verification' content='*****'>
```

**Comment by gaeulbyul** [comment]
I found that another websites with ad-shield code. Again, there's no ads but only the script & analytics code(`<meta name=adshield-analytics-verification>`)

* https://etoland.co.kr
* https://www.op.gg (not on other subdomains (such as overwatch, pubs, valorant, ...))

**Comment by piquark6046** [comment]
https://github.com/List-KR/List-KR-Script/issues/2#issuecomment-1059792208

Okay. I found.

**Comment by piquark6046** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/111644

**Comment by 88Va2wFDcYd1CT** [comment]
Ad-Shield ads from https://ygosu.com/ are not blocked.

**Comment by piquark6046** [comment]
@gaeulbyul @88Va2wFDcYd1CT 
Fetched at List-KR.

https://github.com/List-KR/List-KR/commit/2705e2e5f874d87d14d3570347ed53dc71944a33
https://github.com/List-KR/List-KR/commit/6bc48133f83279ed46ee959b82655088fb3fc83d
